kind: pipeline
type: docker
name: build
steps:
  - name: build # 构建阶段
    image: node:16.13.0
    pull: if-not-exists # 镜像拉取策略
    commands: # 下面这里是我们执行的命令
      - export NODE_OPTIONS="--max-old-space-size=8192"
      - yarn install # 安装依赖
      - yarn run build # 构建应用
  - name: push # 自动推送到私有仓库update
    image: plugins/docker
    pull: if-not-exists # 镜像拉取策略
    settings:
      registry: registry.xiaoyou.host # 私有仓库地址
      repo: registry.xiaoyou.host/mskn/mskn-web # 仓库全称
      use_cache: true
      username: xiaoyou # 设置私有仓库的账号密码
      password: xiaoyou
      tags: # 设置我们的标签
        - 0.0.1